// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTicketsRequest {
    /** Page number for pagination */
    page?: number;
    /** Number of tickets per page */
    per_page?: number;
}
