// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "katzs-deli",
 *         product_id: "product_id",
 *         quantity: 1
 *     }
 */
export interface AddToCartRequest {
    /** The business handle */
    business: string;
    product_id: string;
    variant_id?: string | null;
    quantity: number;
}
