// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "katzs-deli"
 *     }
 */
export interface GetCartRequest {
    /** The business handle */
    business: string;
}
