// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cartItem: "cartItem"
 *     }
 */
export interface RemoveItemCartRequest {
    /** The cart item ID */
    cartItem: string;
}
