// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         shippingRate: "shippingRate"
 *     }
 */
export interface DeleteRatesRequest {
    /** The shipping rate ID */
    shippingRate: string;
}
