// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         event: "event",
 *         order: "order"
 *     }
 */
export interface GetBusinessEventOrderRequest {
    /** The event ID */
    event: string;
    /** The order ID */
    order: string;
}
