// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business_id: "business_id",
 *         message: "message"
 *     }
 */
export interface StoreClaimRequestRequest {
    business_id: string;
    message: string;
}
