// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../src/api/index";
import { FiveOneEatClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("ListsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                lists: [
                    {
                        id: "id",
                        name: "name",
                        description: null,
                        slug: "slug",
                        is_public: true,
                        items_count: 1,
                        created_at: "created_at",
                        updated_at: "updated_at",
                    },
                ],
            },
        };

        server.mockEndpoint().get("/customer/lists").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.me.lists.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/customer/lists").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.me.lists.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            data: {
                id: "id",
                name: "name",
                description: "description",
                slug: "slug",
                is_public: true,
                items_count: 1,
                cover_image: "cover_image",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.me.lists.create({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.create({
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.create({
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/lists")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.create({
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("memberships (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { lists: [{ id: "id", name: "name", is_public: true, contains: true }] } };

        server
            .mockEndpoint()
            .get("/customer/lists/memberships/katzs-deli")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.me.lists.memberships({
            business: "katzs-deli",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("memberships (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/lists/memberships/business")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.memberships({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                name: "name",
                description: "description",
                slug: "slug",
                is_public: true,
                items_count: 1,
                items: [
                    {
                        id: "id",
                        note: null,
                        business: {
                            id: "id",
                            name: "name",
                            handle: "handle",
                            description: null,
                            bio: null,
                            location: { city: null, state: null },
                            logo: null,
                            badges: { founding_partner: true, staff_pick: true },
                            created_at: "created_at",
                        },
                        created_at: "created_at",
                    },
                ],
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/customer/lists/businessList")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.me.lists.get({
            businessList: "businessList",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/lists/businessList")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.get({
                businessList: "businessList",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/lists/businessList")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.get({
                businessList: "businessList",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            data: {
                id: "id",
                name: "name",
                description: "description",
                slug: "slug",
                is_public: true,
                items_count: 1,
                cover_image: "cover_image",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .put("/customer/lists/businessList")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.me.lists.update({
            businessList: "businessList",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/lists/businessList")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.update({
                businessList: "businessList",
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/lists/businessList")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.update({
                businessList: "businessList",
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/lists/businessList")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.update({
                businessList: "businessList",
                name: "name",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/customer/lists/businessList").respondWith().statusCode(200).build();

        const response = await client.customer.me.lists.delete({
            businessList: "businessList",
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/lists/businessList")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.delete({
                businessList: "businessList",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/lists/businessList")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.me.lists.delete({
                businessList: "businessList",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });
});
