// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../src/api/index";
import { FiveOneEatClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("TicketsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                tickets: [
                    { id: "id", ticket_number: "ticket_number", status: "status", qr_code: null, used_at: "used_at" },
                ],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server.mockEndpoint().get("/customer/tickets").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.me.tickets.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/customer/tickets").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.me.tickets.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/customer/tickets").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.me.tickets.list();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/customer/tickets/ticket").respondWith().statusCode(200).build();

        const response = await client.customer.me.tickets.get({
            ticket: "ticket",
        });
        expect(response).toEqual(undefined);
    });
});
