// This file was auto-generated by Fern from our API Definition.

export type GetPickupTimeslotsBusinessesResponse =
    | {
          date?: unknown | undefined;
          timeslots: string[];
      }
    | {
          date?: unknown | undefined;
          timeslots: string[];
      };
