// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { ConversationsClient } from "../resources/conversations/client/Client.js";
import { MessagesClient } from "../resources/messages/client/Client.js";

export declare namespace MessagingClient {
    export type Options = BaseClientOptions;
}

export class MessagingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MessagingClient.Options>;
    protected _conversations: ConversationsClient | undefined;
    protected _messages: MessagesClient | undefined;

    constructor(options: MessagingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get conversations(): ConversationsClient {
        return (this._conversations ??= new ConversationsClient(this._options));
    }

    public get messages(): MessagesClient {
        return (this._messages ??= new MessagesClient(this._options));
    }
}
