// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         product: "product",
 *         name: "name"
 *     }
 */
export interface UpdateProductRequest {
    /** The product ID */
    product: string;
    name: string;
    description?: string | null;
    is_active?: boolean;
    product_category_id?: string | null;
    metadata?: string[] | null;
    channel_ids?: string[] | null;
}
