// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         product: "product",
 *         body: {
 *             images: [{
 *                     id: "id",
 *                     sort_order: 1
 *                 }]
 *         }
 *     }
 */
export interface ReorderImagesRequest {
    /** The product ID */
    product: string;
    body: FiveOneEat.ReorderProductImagesRequest;
}
