// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         menuItem: "menuItem",
 *         modifier: "modifier"
 *     }
 */
export interface DetachModifiersRequest {
    /** The menu item ID */
    menuItem: string;
    /** The modifier ID */
    modifier: string;
}
