// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         handle: "katzs-deli"
 *     }
 */
export interface ProfileShowRequest {
    /** The business handle */
    handle: string;
}
