// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../src/api/index";
import { FiveOneEatClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("TicketTypesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    event_id: "event_id",
                    name: "name",
                    description: "description",
                    price: 1.1,
                    quantity_available: 1,
                    quantity_sold: 1,
                    remaining_quantity: "remaining_quantity",
                    is_available_for_sale: true,
                    sales_start_at: "2024-01-15T09:30:00Z",
                    sales_end_at: "2024-01-15T09:30:00Z",
                    is_active: true,
                    sort_order: 1,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/business/events/event/ticket-types")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.events.ticketTypes.list({
            event: "event",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/events/event/ticket-types")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.list({
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/events/event/ticket-types")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.list({
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/events/event/ticket-types")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.list({
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1, quantity_available: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                event_id: "event_id",
                name: "name",
                description: "description",
                price: 1.1,
                quantity_available: 1,
                quantity_sold: 1,
                remaining_quantity: "remaining_quantity",
                is_available_for_sale: true,
                sales_start_at: "2024-01-15T09:30:00Z",
                sales_end_at: "2024-01-15T09:30:00Z",
                is_active: true,
                sort_order: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/business/events/event/ticket-types")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.events.ticketTypes.create({
            event: "event",
            name: "name",
            price: 1.1,
            quantity_available: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1, quantity_available: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/events/event/ticket-types")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.create({
                event: "event",
                name: "name",
                price: 1.1,
                quantity_available: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1, quantity_available: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/events/event/ticket-types")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.create({
                event: "event",
                name: "name",
                price: 1.1,
                quantity_available: 1,
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1, quantity_available: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/events/event/ticket-types")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.create({
                event: "event",
                name: "name",
                price: 1.1,
                quantity_available: 1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1, quantity_available: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/events/event/ticket-types")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.create({
                event: "event",
                name: "name",
                price: 1.1,
                quantity_available: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                event_id: "event_id",
                name: "name",
                description: "description",
                price: 1.1,
                quantity_available: 1,
                quantity_sold: 1,
                remaining_quantity: "remaining_quantity",
                is_available_for_sale: true,
                sales_start_at: "2024-01-15T09:30:00Z",
                sales_end_at: "2024-01-15T09:30:00Z",
                is_active: true,
                sort_order: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.events.ticketTypes.get({
            ticketType: "ticketType",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.get({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.get({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.get({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                event_id: "event_id",
                name: "name",
                description: "description",
                price: 1.1,
                quantity_available: 1,
                quantity_sold: 1,
                remaining_quantity: "remaining_quantity",
                is_available_for_sale: true,
                sales_start_at: "2024-01-15T09:30:00Z",
                sales_end_at: "2024-01-15T09:30:00Z",
                is_active: true,
                sort_order: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/business/ticket-types/ticketType")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.events.ticketTypes.update({
            ticketType: "ticketType",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/ticket-types/ticketType")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.update({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/ticket-types/ticketType")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.update({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/ticket-types/ticketType")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.update({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/ticket-types/ticketType")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.update({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Ticket type deleted successfully." };

        server
            .mockEndpoint()
            .delete("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.events.ticketTypes.delete({
            ticketType: "ticketType",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.delete({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.delete({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.delete({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/ticket-types/ticketType")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.events.ticketTypes.delete({
                ticketType: "ticketType",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
