// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../../../index.js";

export interface UploadPhotosResponse {
    data: UploadPhotosResponse.Data;
}

export namespace UploadPhotosResponse {
    export interface Data extends FiveOneEat.CustomerBusinessSubmission {}
}
