// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         event: "event"
 *     }
 */
export interface ListOrdersRequest {
    /** The event ID */
    event: string;
}
