// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         product: "product"
 *     }
 */
export interface SummaryInventoryRequest {
    /** The product ID */
    product: string;
}
