// This file was auto-generated by Fern from our API Definition.

export interface DeleteBusinessEventTicketTypeResponse {
    message: DeleteBusinessEventTicketTypeResponse.Message;
}

export namespace DeleteBusinessEventTicketTypeResponse {
    export const Message = {
        TicketTypeDeletedSuccessfully: "Ticket type deleted successfully.",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
