// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../index.js";

export interface ListBusinessEventsResponse {
    data: FiveOneEat.BusinessEvent[];
}
