// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface UpdateBusinessProfileRequest {
    name?: string;
    handle?: string;
    category?: string | null;
    phone?: string | null;
    email?: string | null;
    website?: string | null;
    description?: string | null;
    bio?: string | null;
    facebook_url?: string | null;
    instagram_url?: string | null;
    twitter_url?: string | null;
    tiktok_url?: string | null;
    youtube_url?: string | null;
    linkedin_url?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    has_location?: boolean;
    seasonal?: boolean;
    pickup_enabled?: boolean;
    pickup_hours?: string[] | null;
    same_day_cutoff?: string | null;
    pickup_instructions?: string | null;
    ownership?: string[] | null;
    badges?: string[] | null;
    hours?: UpdateBusinessProfileRequest.Hours.Item[] | null;
    operating_months?: number[] | null;
}

export namespace UpdateBusinessProfileRequest {
    export type Hours = Hours.Item[];

    export namespace Hours {
        export interface Item {
            isOpen?: boolean | undefined;
            openTime?: (string | null) | undefined;
            closeTime?: (string | null) | undefined;
        }
    }
}
