// This file was auto-generated by Fern from our API Definition.

export interface CreatePaymentIntentTicketingResponse {
    data: CreatePaymentIntentTicketingResponse.Data;
}

export namespace CreatePaymentIntentTicketingResponse {
    export interface Data {
        payment_intent_id: string;
        client_secret: string;
        session_id: string;
        subtotal: string;
        platform_fee: string;
        total_amount: string;
    }
}
