// This file was auto-generated by Fern from our API Definition.

import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BusinessesClient", () => {
    test("profile", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/customer/businesses/business").respondWith().statusCode(200).build();

        const response = await client.customer.businesses.profile({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("menus", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/customer/businesses/business/menus").respondWith().statusCode(200).build();

        const response = await client.customer.businesses.menus({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("photos", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/customer/businesses/business/photos").respondWith().statusCode(200).build();

        const response = await client.customer.businesses.photos({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("favorite", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/customer/businesses/business/favorite").respondWith().statusCode(200).build();

        const response = await client.customer.businesses.favorite({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("unfavorite", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/customer/businesses/business/favorite").respondWith().statusCode(200).build();

        const response = await client.customer.businesses.unfavorite({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("listTemporaryLocations", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/customer/businesses/business/temporary-locations")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.customer.businesses.listTemporaryLocations({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });
});
