// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CartClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                business_id: "business_id",
                item_count: 1,
                subtotal: 1.1,
                items: [
                    {
                        id: "id",
                        product_id: "product_id",
                        variant_id: null,
                        quantity: 1,
                        unit_price: 1.1,
                        total_price: 1.1,
                    },
                ],
                expires_at: "2024-01-15T09:30:00Z",
            },
        };

        server.mockEndpoint().get("/customer/cart").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.cart.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/customer/cart").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.cart.get();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("addItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { business_id: 1, product_id: 1, quantity: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                business_id: "business_id",
                item_count: 1,
                subtotal: 1.1,
                items: [
                    {
                        id: "id",
                        product_id: "product_id",
                        variant_id: null,
                        quantity: 1,
                        unit_price: 1.1,
                        total_price: 1.1,
                    },
                ],
                expires_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.addItem({
            business_id: 1,
            product_id: 1,
            quantity: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { business_id: 1, product_id: 1, quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.addItem({
                business_id: 1,
                product_id: 1,
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("addItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { business_id: 1, product_id: 1, quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.addItem({
                business_id: 1,
                product_id: 1,
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("clear (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Cart cleared." };

        server.mockEndpoint().delete("/customer/cart").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.cart.clear();
        expect(response).toEqual(rawResponseBody);
    });

    test("clear (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/customer/cart").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.cart.clear();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("updateItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                business_id: "business_id",
                item_count: 1,
                subtotal: 1.1,
                items: [
                    {
                        id: "id",
                        product_id: "product_id",
                        variant_id: null,
                        quantity: 1,
                        unit_price: 1.1,
                        total_price: 1.1,
                    },
                ],
                expires_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.updateItem({
            cartItem: "cartItem",
            quantity: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("updateItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("updateItem (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quantity: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/customer/cart/items/cartItem")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.updateItem({
                cartItem: "cartItem",
                quantity: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("removeItem (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                business_id: "business_id",
                item_count: 1,
                subtotal: 1.1,
                items: [
                    {
                        id: "id",
                        product_id: "product_id",
                        variant_id: null,
                        quantity: 1,
                        unit_price: 1.1,
                        total_price: 1.1,
                    },
                ],
                expires_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.removeItem({
            cartItem: "cartItem",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeItem (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.removeItem({
                cartItem: "cartItem",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("removeItem (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/cart/items/cartItem")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.removeItem({
                cartItem: "cartItem",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createPaymentIntent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = {
            client_secret: "client_secret",
            payment_intent_id: "payment_intent_id",
            subtotal: 1,
            tax_amount: "tax_amount",
            tax_calculation: { id: "id", amount_total: "amount_total", tax_amount_exclusive: "tax_amount_exclusive" },
            shipping_amount: "shipping_amount",
            shipping_method: "shipping_method",
            platform_fee: "platform_fee",
            total_amount: "total_amount",
        };

        server
            .mockEndpoint()
            .post("/customer/cart/payment-intent")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.createPaymentIntent({
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createPaymentIntent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart/payment-intent")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("createPaymentIntent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart/payment-intent")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("createPaymentIntent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/customer/cart/payment-intent")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.InternalServerError);
    });

    test("createPaymentIntent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/customer/cart/payment-intent")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.createPaymentIntent({
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.ServiceUnavailableError);
    });

    test("checkout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            payment_intent_id: "payment_intent_id",
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = {
            data: {
                id: "id",
                order_number: "order_number",
                status: "status",
                fulfillment_status: "fulfillment_status",
                fulfillment_method: "fulfillment_method",
                subtotal: 1.1,
                tax_amount: 1.1,
                shipping_amount: 1.1,
                discount_amount: 1.1,
                total_amount: 1.1,
                tracking_number: "tracking_number",
                tracking_url: "tracking_url",
                shipping_address: [{ key: "value" }],
                billing_address: [{ key: "value" }],
                business: { id: "id", name: "name", handle: "handle" },
                items: [
                    {
                        id: "id",
                        product_id: "product_id",
                        variant_id: null,
                        quantity: 1,
                        unit_price: 1.1,
                        total_price: 1.1,
                        product_snapshot: null,
                    },
                ],
                payment_completed_at: "2024-01-15T09:30:00Z",
                fulfilled_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.cart.checkout({
            payment_intent_id: "payment_intent_id",
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("checkout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            payment_intent_id: "payment_intent_id",
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                payment_intent_id: "payment_intent_id",
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("checkout (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            payment_intent_id: "payment_intent_id",
            billing_address: {
                line1: "line1",
                city: "city",
                state: "state",
                postal_code: "postal_code",
                country: "country",
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/cart/checkout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.cart.checkout({
                payment_intent_id: "payment_intent_id",
                billing_address: {
                    line1: "line1",
                    city: "city",
                    state: "state",
                    postal_code: "postal_code",
                    country: "country",
                },
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
