// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("DiscoveryClient", () => {
    test("feed (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    value: "value",
                    label: "label",
                    total_businesses: 1,
                    businesses: [
                        {
                            id: "id",
                            name: "name",
                            handle: "handle",
                            description: null,
                            bio: null,
                            location: { city: null, state: null },
                            logo: null,
                            photos: [{ id: "id", url: "url", alt_text: null }],
                            has_bulletins: true,
                            latest_bulletin: null,
                            badges: { founding_partner: true, staff_pick: true },
                            created_at: "created_at",
                        },
                    ],
                },
            ],
            meta: { current_page: "current_page", per_page: "per_page", total: "total", has_more: "has_more" },
        };

        server
            .mockEndpoint()
            .get("/customer/discovery")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.feed({
            search: "organic",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("feed (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.feed();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("feed (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.feed();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("highlights (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                staff_picks: [
                    {
                        id: "id",
                        name: "name",
                        handle: "handle",
                        description: null,
                        bio: null,
                        location: { city: null, state: null },
                        logo: null,
                        photos: [{ id: "id", url: "url", alt_text: null }],
                        has_bulletins: true,
                        latest_bulletin: null,
                        badges: { founding_partner: true, staff_pick: true },
                        created_at: "created_at",
                    },
                ],
                founding_partners: [
                    {
                        id: "id",
                        name: "name",
                        handle: "handle",
                        description: null,
                        bio: null,
                        location: { city: null, state: null },
                        logo: null,
                        photos: [{ id: "id", url: "url", alt_text: null }],
                        has_bulletins: true,
                        latest_bulletin: null,
                        badges: { founding_partner: true, staff_pick: true },
                        created_at: "created_at",
                    },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/customer/discovery/highlights")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.highlights();
        expect(response).toEqual(rawResponseBody);
    });

    test("highlights (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/highlights")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.highlights();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("categories (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: 1,
                    name: "name",
                    slug: "slug",
                    description: "description",
                    icon: "icon",
                    group: "group",
                    business_count: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/discovery/categories")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.categories();
        expect(response).toEqual(rawResponseBody);
    });

    test("categories (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/categories")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.categories();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("cuisines (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { data: [{ id: 1, name: "name", slug: "slug", description: "description" }] };

        server
            .mockEndpoint()
            .get("/customer/discovery/cuisines")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.cuisines();
        expect(response).toEqual(rawResponseBody);
    });

    test("cuisines (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/cuisines")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.cuisines();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("certifications (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ id: 1, name: "name", slug: "slug", description: "description", icon: "icon" }],
        };

        server
            .mockEndpoint()
            .get("/customer/discovery/certifications")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.certifications();
        expect(response).toEqual(rawResponseBody);
    });

    test("certifications (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/certifications")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.certifications();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("allergens (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ id: "id", name: "name", slug: "slug", icon: "icon", description: "description", color: "color" }],
        };

        server
            .mockEndpoint()
            .get("/customer/discovery/allergens")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.allergens();
        expect(response).toEqual(rawResponseBody);
    });

    test("allergens (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/allergens")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.allergens();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("categoryBusinesses (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                businesses: [
                    {
                        id: "id",
                        name: "name",
                        handle: "handle",
                        description: null,
                        bio: null,
                        location: { city: null, state: null },
                        logo: null,
                        photos: [{ id: "id", url: "url", alt_text: null }],
                        has_bulletins: true,
                        latest_bulletin: null,
                        badges: { founding_partner: true, staff_pick: true },
                        created_at: "created_at",
                    },
                ],
                category: "category",
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
                filters: { category: "category", search: "search" },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/discovery/category/restaurant/businesses")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.discovery.categoryBusinesses({
            category: "restaurant",
            search: "coffee",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("categoryBusinesses (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/category/category/businesses")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.categoryBusinesses({
                category: "category",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("categoryBusinesses (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/discovery/category/category/businesses")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.discovery.categoryBusinesses({
                category: "category",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
