// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EditorialsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    author: "author",
                    excerpt: "excerpt",
                    business: {
                        id: "id",
                        name: "name",
                        handle: "handle",
                        logo: null,
                        photos: [{ id: "id", url: "url", alt_text: null }],
                    },
                    published_at: "published_at",
                    created_at: "created_at",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/editorials")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.editorials.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/editorials")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.editorials.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                slug: "slug",
                title: "title",
                author: "author",
                excerpt: "excerpt",
                body: { key: "value" },
                business: {
                    id: "id",
                    name: "name",
                    handle: "handle",
                    description: "description",
                    bio: "bio",
                    category: "category",
                    email: "email",
                    phone: "phone",
                    website: "website",
                    address: "address",
                    city: "city",
                    state: "state",
                    zip: "zip",
                    country: "country",
                    latitude: 1.1,
                    longitude: 1.1,
                    has_location: true,
                    facebook_url: "facebook_url",
                    instagram_url: "instagram_url",
                    twitter_url: "twitter_url",
                    tiktok_url: "tiktok_url",
                    youtube_url: "youtube_url",
                    linkedin_url: "linkedin_url",
                    logo: "logo",
                    cover_photo: "cover_photo",
                    hours: { key: { isOpen: true, openTime: "openTime", closeTime: "closeTime" } },
                    seasonal: true,
                    operating_months: ["operating_months"],
                    ownership: ["ownership"],
                    badges: ["badges"],
                    metadata: { key: "value" },
                    founding_partner: true,
                    staff_pick: true,
                    favorites_count: 1,
                    is_favorited: true,
                    cuisines: [{ id: "id", name: "name", slug: "slug" }],
                    certifications: [{ id: 1, name: "name", slug: "slug", icon: null }],
                    temporary_locations: [
                        {
                            id: "id",
                            title: "title",
                            notes: null,
                            address: null,
                            city: null,
                            state: null,
                            zip: null,
                            country: null,
                            latitude: null,
                            longitude: null,
                            hours: { key: "value" },
                            starts_at: "2024-01-15T09:30:00Z",
                            ends_at: "2024-01-15T09:30:00Z",
                        },
                    ],
                },
                published_at: "published_at",
                created_at: "created_at",
            },
        };

        server
            .mockEndpoint()
            .get("/customer/editorials/slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.editorials.get({
            slug: "slug",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/editorials/slug")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.editorials.get({
                slug: "slug",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });
});
