// This file was auto-generated by Fern from our API Definition.

import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EditorialsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    author: "author",
                    excerpt: "excerpt",
                    business: {
                        id: "id",
                        name: "name",
                        handle: "handle",
                        logo: null,
                        photos: [{ id: "id", url: "url", alt_text: null }],
                    },
                    published_at: "published_at",
                    created_at: "created_at",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/editorials")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.editorials.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                slug: "slug",
                title: "title",
                author: "author",
                excerpt: "excerpt",
                body: { key: "value" },
                business: {
                    id: "id",
                    name: "name",
                    handle: "handle",
                    description: "description",
                    bio: "bio",
                    email: "email",
                    phone: "phone",
                    website: "website",
                    address: "address",
                    city: "city",
                    state: "state",
                    zip: "zip",
                    country: "country",
                    latitude: 1.1,
                    longitude: 1.1,
                    has_location: true,
                    facebook_url: "facebook_url",
                    instagram_url: "instagram_url",
                    twitter_url: "twitter_url",
                    tiktok_url: "tiktok_url",
                    youtube_url: "youtube_url",
                    linkedin_url: "linkedin_url",
                    logo: "logo",
                    cover_photo: "cover_photo",
                    hours: {
                        is_open_now: "is_open_now",
                        next_open_at: null,
                        schedule: [
                            {
                                day: "day",
                                slots: [{ opens_at: "opens_at", closes_at: "closes_at", label: null, sort_order: 1 }],
                            },
                        ],
                        exceptions: [
                            {
                                id: "id",
                                starts_on: "starts_on",
                                ends_on: null,
                                is_closed: true,
                                opens_at: null,
                                closes_at: null,
                                label: null,
                                message: null,
                            },
                        ],
                    },
                    seasonal: true,
                    operating_months: ["operating_months"],
                    founding_partner: true,
                    staff_pick: true,
                    favorites_count: 1,
                    is_favorited: true,
                    categories: [
                        {
                            id: 1,
                            name: "name",
                            slug: "slug",
                            description: null,
                            icon: null,
                            group: "group",
                            sort_order: 1,
                        },
                    ],
                    cuisines: [{ id: "id", name: "name", slug: "slug" }],
                    certifications: [{ id: 1, name: "name", slug: "slug", icon: null }],
                    temporary_locations: [
                        {
                            id: "id",
                            title: "title",
                            notes: null,
                            address: null,
                            city: null,
                            state: null,
                            zipcode: null,
                            country: null,
                            latitude: null,
                            longitude: null,
                            hours: { key: { isOpen: true, openTime: "openTime", closeTime: "closeTime" } },
                            starts_at: "starts_at",
                            ends_at: "ends_at",
                        },
                    ],
                },
                published_at: "published_at",
                created_at: "created_at",
            },
        };

        server
            .mockEndpoint()
            .get("/customer/editorials/slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.editorials.get({
            slug: "slug",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
