// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ProductOrdersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    order_number: "order_number",
                    status: "status",
                    fulfillment_status: "fulfillment_status",
                    fulfillment_method: "fulfillment_method",
                    subtotal_cents: 1,
                    discount_cents: 1,
                    shipping_cents: 1,
                    tax_cents: 1,
                    platform_fee_cents: 1,
                    total_cents: 1,
                    currency: "currency",
                    shipping_address: { key: "value" },
                    notes: "notes",
                    fulfilled_at: "fulfilled_at",
                    refunded_at: "refunded_at",
                    business: { id: "id", handle: "handle", name: "name" },
                    transaction: {
                        ulid: "ulid",
                        status: "status",
                        refunded_amount_cents: 1,
                        payment_completed_at: "payment_completed_at",
                        refunded_at: "refunded_at",
                    },
                    tracking_number: "tracking_number",
                    tracking_url: "tracking_url",
                    shipments: "shipments",
                    items: [{ id: "id", variant_id: "variant_id", quantity: 1, unit_price_cents: 1, total_cents: 1 }],
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/product-orders")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.productOrders.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/product-orders")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.productOrders.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                order_number: "order_number",
                status: "status",
                fulfillment_status: "fulfillment_status",
                fulfillment_method: "fulfillment_method",
                subtotal_cents: 1,
                discount_cents: 1,
                shipping_cents: 1,
                tax_cents: 1,
                platform_fee_cents: 1,
                total_cents: 1,
                currency: "currency",
                shipping_address: { key: "value" },
                notes: "notes",
                fulfilled_at: "fulfilled_at",
                refunded_at: "refunded_at",
                business: { id: "id", handle: "handle", name: "name" },
                transaction: {
                    ulid: "ulid",
                    status: "status",
                    refunded_amount_cents: 1,
                    payment_completed_at: "payment_completed_at",
                    refunded_at: "refunded_at",
                },
                tracking_number: "tracking_number",
                tracking_url: "tracking_url",
                shipments: "shipments",
                items: [{ id: "id", variant_id: "variant_id", quantity: 1, unit_price_cents: 1, total_cents: 1 }],
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/customer/product-orders/productOrder")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.productOrders.get({
            productOrder: "productOrder",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/product-orders/productOrder")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.productOrders.get({
                productOrder: "productOrder",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/product-orders/productOrder")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.productOrders.get({
                productOrder: "productOrder",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });
});
