// This file was auto-generated by Fern from our API Definition.

import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ShopClient", () => {
    test("listProducts", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/customer/businesses/business/shop").respondWith().statusCode(200).build();

        const response = await client.customer.shop.listProducts({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });

    test("getProduct", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/customer/businesses/business/shop/products/product")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.customer.shop.getProduct({
            business: "business",
            product: "product",
        });
        expect(response).toEqual(undefined);
    });

    test("listCategories", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/customer/businesses/business/shop/categories")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.customer.shop.listCategories({
            business: "business",
        });
        expect(response).toEqual(undefined);
    });
});
