// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("StandsClient", () => {
    test("scan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                stand: {
                    id: "id",
                    name: "name",
                    address: "address",
                    city: "city",
                    state: "state",
                    latitude: "latitude",
                    longitude: "longitude",
                    notes: "notes",
                },
                business: { id: "id", handle: "handle", name: "name", accepts_payments: true },
                products: [
                    {
                        id: "id",
                        name: "name",
                        slug: "slug",
                        description: "description",
                        is_active: "is_active",
                        published_at: "published_at",
                        metadata: "metadata",
                        product_category_id: "product_category_id",
                        created_at: "created_at",
                        updated_at: "updated_at",
                    },
                ],
            },
        };

        server.mockEndpoint().get("/stand/stand").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.stands.scan({
            stand: "stand",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("scan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/stand/stand").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.customer.stands.scan({
                stand: "stand",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("checkout", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/customer/stands/stand/checkout").respondWith().statusCode(200).build();

        const response = await client.customer.stands.checkout({
            stand: "stand",
        });
        expect(response).toEqual(undefined);
    });

    test("createPaymentIntent", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/customer/stands/stand/payment-intent").respondWith().statusCode(200).build();

        const response = await client.customer.stands.createPaymentIntent({
            stand: "stand",
        });
        expect(response).toEqual(undefined);
    });
});
