// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../../src/api/index";
import { FiveOneEatClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("InventoryClient", () => {
    test("adjust (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", adjustment: 1 };
        const rawResponseBody = {
            data: {
                id: "id",
                sales_channel_id: "sales_channel_id",
                quantity: "quantity",
                tracks_inventory: "tracks_inventory",
                allows_holds: "allows_holds",
            },
        };

        server
            .mockEndpoint()
            .post("/business/products/variants/variant/inventory/adjust")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.products.variants.inventory.adjust({
            variant: "variant",
            sales_channel_id: "sales_channel_id",
            adjustment: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("adjust (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", adjustment: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/products/variants/variant/inventory/adjust")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.adjust({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                adjustment: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("adjust (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", adjustment: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/products/variants/variant/inventory/adjust")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.adjust({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                adjustment: 1,
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("adjust (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", adjustment: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/products/variants/variant/inventory/adjust")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.adjust({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                adjustment: 1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("adjust (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", adjustment: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/products/variants/variant/inventory/adjust")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.adjust({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                adjustment: 1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("updateTracking (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", tracks_inventory: true };
        const rawResponseBody = {
            data: {
                id: "id",
                sales_channel_id: "sales_channel_id",
                quantity: "quantity",
                tracks_inventory: "tracks_inventory",
                allows_holds: "allows_holds",
            },
        };

        server
            .mockEndpoint()
            .patch("/business/products/variants/variant/inventory/tracking")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.products.variants.inventory.updateTracking({
            variant: "variant",
            sales_channel_id: "sales_channel_id",
            tracks_inventory: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateTracking (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", tracks_inventory: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/business/products/variants/variant/inventory/tracking")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.updateTracking({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                tracks_inventory: true,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("updateTracking (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", tracks_inventory: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/business/products/variants/variant/inventory/tracking")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.updateTracking({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                tracks_inventory: true,
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("updateTracking (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", tracks_inventory: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/business/products/variants/variant/inventory/tracking")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.updateTracking({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                tracks_inventory: true,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("updateTracking (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { sales_channel_id: "sales_channel_id", tracks_inventory: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/business/products/variants/variant/inventory/tracking")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.products.variants.inventory.updateTracking({
                variant: "variant",
                sales_channel_id: "sales_channel_id",
                tracks_inventory: true,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("history", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/business/products/variants/variant/inventory/history")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.business.products.variants.inventory.history({
            variant: "variant",
        });
        expect(response).toEqual(undefined);
    });
});
