// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../../index.js";

/**
 * @example
 *     {
 *         stand: "stand",
 *         body: {
 *             payment_intent_id: "payment_intent_id"
 *         }
 *     }
 */
export interface CheckoutStandsRequest {
    /** The stand ID */
    stand: string;
    body: FiveOneEat.CheckoutRequest;
}
