// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         temporaryLocation: "temporaryLocation"
 *     }
 */
export interface UpdateTemporaryLocationRequest {
    /** The temporary location ID */
    temporaryLocation: string;
    title?: string;
    notes?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    hours?: string[] | null;
    starts_at?: string;
    ends_at?: string;
}
