// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { AccountClient } from "../resources/account/client/Client.js";
import { RatesClient } from "../resources/rates/client/Client.js";

export declare namespace ShippingClient {
    export type Options = BaseClientOptions;
}

export class ShippingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ShippingClient.Options>;
    protected _account: AccountClient | undefined;
    protected _rates: RatesClient | undefined;

    constructor(options: ShippingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get rates(): RatesClient {
        return (this._rates ??= new RatesClient(this._options));
    }
}
