// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../index.js";

export interface CustomerGetStandCartResponse {
    data: FiveOneEat.CartResource;
}
