// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bulletin: "bulletin"
 *     }
 */
export interface DeleteBulletinsRequest {
    /** The bulletin ID */
    bulletin: string;
}
