// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         variant: "variant"
 *     }
 */
export interface DeleteVariantsRequest {
    /** The variant ID */
    variant: string;
}
