// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         menu: "menu"
 *     }
 */
export interface GetMenusRequest {
    /** The menu ID */
    menu: string;
}
