// This file was auto-generated by Fern from our API Definition.

export interface Address {
    id: number;
    label: string | null;
    line1: string;
    line2: string | null;
    city: string;
    state: string;
    postal_code: string;
    country: string;
    latitude: number | null;
    longitude: number | null;
    is_default: boolean;
    created_at: string | null;
    updated_at: string | null;
}
