// This file was auto-generated by Fern from our API Definition.

export interface AppHttpResourcesApiV1BusinessAuthTokenResource {
    id: string;
    name: string;
    last_used_at: string;
    created_at: string;
}
