// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface AppHttpResourcesApiV1BusinessProfileBusinessProfileResource {
    id: string;
    name: string;
    handle: string;
    category: string | null;
    description: string | null;
    bio: string | null;
    email: string | null;
    phone: string | null;
    website: string | null;
    facebook_url: string | null;
    instagram_url: string | null;
    twitter_url: string | null;
    tiktok_url: string | null;
    youtube_url: string | null;
    linkedin_url: string | null;
    address: string | null;
    city: string | null;
    state: string | null;
    zipcode: string | null;
    country: string | null;
    latitude: number | null;
    longitude: number | null;
    has_location: boolean;
    logo: string | null;
    logo_url: string | null;
    hours: Record<string, AppHttpResourcesApiV1BusinessProfileBusinessProfileResource.Hours.Value>;
    seasonal: boolean;
    operating_months: number[];
    pickup_enabled: boolean;
    pickup_hours: Record<string, unknown>;
    same_day_cutoff: string | null;
    pickup_instructions: string | null;
    ownership: string[];
    badges: string[];
    founding_partner: boolean;
    staff_pick: boolean;
    favorites_count: number;
    cuisines?: AppHttpResourcesApiV1BusinessProfileBusinessProfileResource.Cuisines.Item[] | undefined;
    certifications?: AppHttpResourcesApiV1BusinessProfileBusinessProfileResource.Certifications.Item[] | undefined;
    active_temporary_locations?: FiveOneEat.TemporaryLocationResource[] | undefined;
}

export namespace AppHttpResourcesApiV1BusinessProfileBusinessProfileResource {
    export namespace Hours {
        export interface Value {
            isOpen: boolean;
            openTime: string;
            closeTime: string;
        }
    }

    export type Cuisines = Cuisines.Item[];

    export namespace Cuisines {
        export interface Item {
            id: string;
            name: string;
            slug: string;
        }
    }

    export type Certifications = Certifications.Item[];

    export namespace Certifications {
        export interface Item {
            id: number;
            name: string;
            slug: string;
            icon: string | null;
        }
    }
}
