// This file was auto-generated by Fern from our API Definition.

export interface BardEventSetValues {
    caption: string | null;
    item: BardEventSetValues.Item | null;
}

export namespace BardEventSetValues {
    export interface Item {
        id: string;
        title: string;
        description?: (string | null) | undefined;
        starts_at?: (string | null) | undefined;
        ends_at?: (string | null) | undefined;
        location?: (string | null) | undefined;
        image?: (string | null) | undefined;
    }
}
