// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export type BardSetValues =
    | FiveOneEat.BardSetValues.MenuItem
    | FiveOneEat.BardSetValues.Product
    | FiveOneEat.BardSetValues.Event
    | FiveOneEat.BardSetValues.PullQuote
    | FiveOneEat.BardSetValues.PhotoSpread
    | FiveOneEat.BardSetValues.Ingredient
    | FiveOneEat.BardSetValues.TastingNotes;

export namespace BardSetValues {
    export interface MenuItem extends FiveOneEat.BardMenuItemSetValues {
        type: "menu_item";
    }

    export interface Product extends FiveOneEat.BardProductSetValues {
        type: "product";
    }

    export interface Event extends FiveOneEat.BardEventSetValues {
        type: "event";
    }

    export interface PullQuote extends FiveOneEat.BardPullQuoteSetValues {
        type: "pull_quote";
    }

    export interface PhotoSpread extends FiveOneEat.BardPhotoSpreadSetValues {
        type: "photo_spread";
    }

    export interface Ingredient extends FiveOneEat.BardIngredientSetValues {
        type: "ingredient";
    }

    export interface TastingNotes extends FiveOneEat.BardTastingNotesSetValues {
        type: "tasting_notes";
    }
}
