// This file was auto-generated by Fern from our API Definition.

export interface BusinessMenuItemModifier {
    id: string;
    name: string;
    description: string;
    price: string;
    is_default: string;
}
