// This file was auto-generated by Fern from our API Definition.

export interface BusinessEventTicketType {
    id: string;
    event_id: string;
    name: string;
    description: string | null;
    price: number;
    quantity_available: number;
    quantity_sold: number;
    remaining_quantity: string;
    is_available_for_sale: boolean;
    sales_start_at: string | null;
    sales_end_at: string | null;
    is_active: boolean;
    sort_order: number;
    created_at: string | null;
    updated_at: string | null;
}
