// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface BusinessMenu {
    id: string;
    name: string;
    description: string | null;
    groups?: FiveOneEat.BusinessMenuGroup[] | undefined;
}
