// This file was auto-generated by Fern from our API Definition.

export interface BusinessClaimRequest {
    id: string;
    business_id: string;
    message: string;
    status: string;
    rejected_reason: string;
    created_at: string;
    reviewed_at: string;
}
