// This file was auto-generated by Fern from our API Definition.

export interface BusinessMenuItemVariation {
    id: string;
    menu_item_id: string;
    name: string;
    description: string | null;
    price: number | null;
    is_default: boolean;
    sort_order: number;
}
