// This file was auto-generated by Fern from our API Definition.

export interface BusinessDiscount {
    id: string;
    code: string;
    type: string;
    value: number;
    minimum_purchase: number | null;
    maximum_discount: number | null;
    applies_to: string;
    usage_limit: number | null;
    usage_limit_per_customer: number | null;
    usage_count?: number | undefined;
    is_active: boolean;
    starts_at: string | null;
    ends_at: string | null;
    products?: Record<string, unknown>[] | undefined;
    categories?: Record<string, unknown>[] | undefined;
    created_at: string | null;
    updated_at: string | null;
}
