// This file was auto-generated by Fern from our API Definition.

export interface BusinessEventOrder {
    id: string;
    event_id: string;
    order_number: string;
    status: string;
    subtotal: string;
    fees: string;
    total_amount: string;
    refunded_amount: string;
    remaining_refundable_amount: string;
    customer_name: string;
    customer_email: string;
    payment_completed_at: string;
    refunded_at: string;
    tickets_count?: number | undefined;
    user?: BusinessEventOrder.User | undefined;
    created_at: string;
    updated_at: string;
}

export namespace BusinessEventOrder {
    export interface User {
        id: string;
        name: string;
        email: string;
    }
}
