// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface BusinessEvent {
    id: string;
    business_id: string;
    title: string;
    description: string | null;
    starts_at: string;
    ends_at: string;
    location: string | null;
    is_all_day: boolean;
    is_featured: boolean;
    ticket_sales_enabled: boolean;
    is_published: boolean;
    published_at: string | null;
    sort_order: number;
    image?: string | undefined;
    ticket_types?: FiveOneEat.BusinessEventTicketType[] | undefined;
    rsvps_count?: number | undefined;
    attendees_count?: number | undefined;
    tickets_count?: number | undefined;
    created_at: string | null;
    updated_at: string | null;
}
