// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface BusinessProduct {
    id: string;
    name: string;
    slug: string;
    description: string | null;
    product_type: string;
    base_price: number;
    compare_at_price: number | null;
    sku: string | null;
    track_inventory: boolean;
    inventory_policy: string | null;
    fulfillment_type: string | null;
    requires_shipping: boolean;
    length: number | null;
    width: number | null;
    height: number | null;
    dimension_unit: string | null;
    weight: number | null;
    weight_unit: string | null;
    is_pre_order: boolean;
    pre_order_release_date: string | null;
    digital_download_limit: number | null;
    digital_link_expiry_hours: number | null;
    taxable: boolean;
    tax_code: string | null;
    is_active: boolean;
    is_featured: boolean;
    sort_order: number;
    published_at: string | null;
    variants?: FiveOneEat.BusinessProductVariant[] | undefined;
    images?: FiveOneEat.BusinessPhoto[] | undefined;
    categories?: FiveOneEat.BusinessProductCategory[] | undefined;
    digital_files?: BusinessProduct.DigitalFiles.Item[] | undefined;
    created_at: string | null;
    updated_at: string | null;
}

export namespace BusinessProduct {
    export type DigitalFiles = DigitalFiles.Item[];

    export namespace DigitalFiles {
        export interface Item {
            id: string;
            file_name: string;
        }
    }
}
