// This file was auto-generated by Fern from our API Definition.

export interface BusinessEventCheckIn {
    id: string;
    ticket_number: string;
    checked_in_at: string;
    checked_in_by: string;
    user?: BusinessEventCheckIn.User | undefined;
    ticket_type?: BusinessEventCheckIn.TicketType | undefined;
}

export namespace BusinessEventCheckIn {
    export interface User {
        id: string;
        name: string;
    }

    export interface TicketType {
        id: string;
        name: string;
    }
}
