// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface BusinessProductOrder {
    id: string;
    order_number: string;
    status: string;
    fulfillment_status: string;
    fulfillment_method: string | null;
    fulfillment_type: string | null;
    discount_amount: number;
    transaction?: FiveOneEat.Transaction | undefined;
    customer_phone: string | null;
    shipping_address: Record<string, unknown> | null;
    billing_address: Record<string, unknown> | null;
    tracking_number: string | null;
    tracking_url: string | null;
    pickup_date: string | null;
    pickup_time: string | null;
    user?: BusinessProductOrder.User | undefined;
    items?: FiveOneEat.BusinessProductOrderItem[] | undefined;
    shipment?: (BusinessProductOrder.Shipment | null) | undefined;
    fulfilled_at: string | null;
    picked_up_at: string | null;
    created_at: string | null;
    updated_at: string | null;
}

export namespace BusinessProductOrder {
    export interface User {
        id: string;
        name: string;
        email: string;
    }

    export interface Shipment {
        id: string;
        carrier: string | null;
        tracking_number: string | null;
        tracking_url: string | null;
        status: string | null;
        shipped_at: string | null;
    }
}
