// This file was auto-generated by Fern from our API Definition.

export interface CheckoutRequest {
    payment_intent_id: string;
    pickup_date?: (string | null) | undefined;
    pickup_time?: (string | null) | undefined;
}
