// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface CustomerProductOrder {
    id: string;
    order_number: string;
    status: string;
    fulfillment_status: string;
    fulfillment_method: string;
    subtotal: number;
    tax_amount: number;
    shipping_amount: number;
    discount_amount: number;
    total_amount: number;
    tracking_number: string | null;
    tracking_url: string | null;
    shipping_address: unknown[] | null;
    billing_address: unknown[] | null;
    business?: CustomerProductOrder.Business | undefined;
    items?: FiveOneEat.CustomerProductOrderItem[] | undefined;
    payment_completed_at: string | null;
    fulfilled_at: string | null;
    created_at: string | null;
}

export namespace CustomerProductOrder {
    export interface Business {
        id: string;
        name: string;
        handle: string;
    }
}
