// This file was auto-generated by Fern from our API Definition.

export interface CustomerBusinessSubmission {
    id: string;
    name: string;
    address: string;
    city: string;
    state: string;
    zipcode: string;
    country: string;
    latitude: string;
    longitude: string;
    phone: string;
    website: string;
    description: string;
    status: string;
    source: string;
    rejected_reason: string;
    submitted_at: string;
    photos?: string | undefined;
}
