// This file was auto-generated by Fern from our API Definition.

export interface CustomerEventTicketType {
    id: string;
    name: string;
    description: string | null;
    price: string;
    remaining_quantity: number | null;
    is_available_for_sale: boolean;
    sales_start_at: string | null;
    sales_end_at: string | null;
}
