// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface CustomerBusinessProfile {
    id: string;
    name: string;
    handle: string;
    description: string | null;
    bio: string | null;
    email: string | null;
    phone: string | null;
    website: string | null;
    address: string | null;
    city: string | null;
    state: string | null;
    zip: string | null;
    country: string | null;
    latitude: number | null;
    longitude: number | null;
    has_location: boolean;
    facebook_url: string | null;
    instagram_url: string | null;
    twitter_url: string | null;
    tiktok_url: string | null;
    youtube_url: string | null;
    linkedin_url: string | null;
    logo: string | null;
    cover_photo?: (string | null) | undefined;
    hours: Record<string, CustomerBusinessProfile.Hours.Value>;
    seasonal: boolean;
    operating_months: string[];
    ownership: string[];
    badges: string[];
    metadata: Record<string, unknown>;
    founding_partner: boolean;
    staff_pick: boolean;
    favorites_count: number;
    is_favorited: boolean;
    categories?: FiveOneEat.BusinessCategory[] | undefined;
    cuisines?: CustomerBusinessProfile.Cuisines.Item[] | undefined;
    certifications?: CustomerBusinessProfile.Certifications.Item[] | undefined;
    temporary_locations?: FiveOneEat.CustomerTemporaryLocation[] | undefined;
}

export namespace CustomerBusinessProfile {
    export namespace Hours {
        export interface Value {
            isOpen: boolean;
            openTime: string;
            closeTime: string;
        }
    }

    export type Cuisines = Cuisines.Item[];

    export namespace Cuisines {
        export interface Item {
            id: string;
            name: string;
            slug: string;
        }
    }

    export type Certifications = Certifications.Item[];

    export namespace Certifications {
        export interface Item {
            id: number;
            name: string;
            slug: string;
            icon: string | null;
        }
    }
}
