// This file was auto-generated by Fern from our API Definition.

export interface CustomerProductOrderItem {
    id: string;
    product_id: string;
    variant_id: string | null;
    quantity: number;
    unit_price: number;
    total_price: number;
    product_snapshot: unknown[] | null;
    product?: CustomerProductOrderItem.Product | undefined;
    variant?: (CustomerProductOrderItem.Variant | null) | undefined;
    downloads?: string | undefined;
}

export namespace CustomerProductOrderItem {
    export interface Product {
        id: string;
        name: string;
        product_type: string;
    }

    export interface Variant {
        id: string;
        name: string;
    }
}
