// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface DiscoveryResponseResource {
    businesses: FiveOneEat.DiscoveryBusinessResource[];
    category: string;
    pagination: FiveOneEat.PaginationResource;
    filters: DiscoveryResponseResource.Filters;
}

export namespace DiscoveryResponseResource {
    export interface Filters {
        category: string;
        search: string;
    }
}
