// This file was auto-generated by Fern from our API Definition.

export interface DiscoveryBusinessResource {
    id: string;
    name: string;
    handle: string;
    category: string | null;
    description: string | null;
    bio: string | null;
    location: DiscoveryBusinessResource.Location;
    logo: string | null;
    photos: DiscoveryBusinessResource.Photos.Item[];
    has_bulletins: boolean;
    latest_bulletin: DiscoveryBusinessResource.LatestBulletin | null;
    badges: DiscoveryBusinessResource.Badges;
    created_at: string;
    editorial?: (DiscoveryBusinessResource.Editorial | null) | undefined;
}

export namespace DiscoveryBusinessResource {
    export interface Location {
        city: string | null;
        state: string | null;
    }

    export type Photos = Photos.Item[];

    export namespace Photos {
        export interface Item {
            id: string;
            url: string;
            alt_text: string | null;
        }
    }

    export interface LatestBulletin {
        title: string | null;
        content: string | null;
        published_at?: unknown | undefined;
    }

    export interface Badges {
        founding_partner: boolean;
        staff_pick: boolean;
    }

    export interface Editorial {
        slug: string;
        title: string;
        excerpt: string | null;
    }
}
