// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface DiscoveryCategoryItem {
    value: string;
    label: string;
    total_businesses: number;
    businesses: FiveOneEat.DiscoveryBusiness[];
}
