// This file was auto-generated by Fern from our API Definition.

export interface EditorialSummaryResource {
    id: string;
    slug: string;
    title: string;
    author: string | null;
    excerpt: string | null;
    business: EditorialSummaryResource.Business;
    published_at: string | null;
    created_at: string;
}

export namespace EditorialSummaryResource {
    export interface Business {
        id: string;
        name: string;
        handle: string;
        logo: string | null;
        photos: Business.Photos.Item[];
    }

    export namespace Business {
        export type Photos = Photos.Item[];

        export namespace Photos {
            export interface Item {
                id: string;
                url: string;
                alt_text: string | null;
            }
        }
    }
}
