// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface Editorial {
    id: string;
    slug: string;
    title: string;
    author: string | null;
    excerpt: string | null;
    /** Augmented ProseMirror node tree. Schema defined in App\OpenApi\BardSchemas. */
    body: Record<string, unknown> | null;
    business: FiveOneEat.CustomerBusinessProfile;
    published_at: string | null;
    created_at: string;
}
