// This file was auto-generated by Fern from our API Definition.

export interface ExploreEvent {
    id: string;
    title: string;
    description: string | null;
    location: string | null;
    starts_at: string;
    ends_at: string;
    latitude: number | null;
    longitude: number | null;
    is_featured: boolean;
    business?: ExploreEvent.Business | undefined;
}

export namespace ExploreEvent {
    export interface Business {
        id: string;
        name: string;
        handle: string;
        logo: string;
        category: string;
    }
}
