// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface FavoriteResponse {
    businesses: FiveOneEat.CustomerBusinessProfile[];
    pagination: FiveOneEat.PaginationResource;
}
