// This file was auto-generated by Fern from our API Definition.

export interface Message {
    id: string;
    conversation_id: string;
    sender_id: string;
    sender?: Message.Sender | undefined;
    content: string;
    message_type: string;
    metadata: Record<string, unknown> | null;
    is_read: boolean;
    is_edited: boolean;
    edited_at: string | null;
    created_at: string;
    updated_at: string;
}

export namespace Message {
    export interface Sender {
        id: string;
        name: string;
        email: string;
    }
}
