// This file was auto-generated by Fern from our API Definition.

export interface OrderResource {
    id: string;
    order_number: string;
    status: string;
    fulfillment_status: string;
    fulfillment_method: string;
    subtotal_cents: string;
    discount_cents: string;
    shipping_cents: string;
    tax_cents: string;
    platform_fee_cents: OrderResource.PlatformFeeCents;
    total_cents: string;
    currency: string;
    shipping_address: string;
    notes: string;
    fulfilled_at: string;
    refunded_at: string;
    tracking_number?: (string | null) | undefined;
    shipments: OrderResource.Shipments;
    items: unknown[];
    created_at: string;
    updated_at: string;
}

export namespace OrderResource {
    export type PlatformFeeCents = string | number;
    export type Shipments = string | string[];
}
