// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../index.js";

export interface PublicBusinessList {
    id: string;
    name: string;
    description: string | null;
    slug: string;
    owner_name: string;
    items?: FiveOneEat.BusinessListItem[] | undefined;
    created_at: string;
}
