// This file was auto-generated by Fern from our API Definition.

export interface Transaction {
    ulid: string;
    status: string;
    subtotal: string;
    tax_amount: string;
    shipping_amount: string;
    platform_fee: string;
    total_amount: string;
    refunded_amount: string;
    customer_name: string | null;
    customer_email: string;
    stripe_payment_intent_id: string | null;
    payment_completed_at: string | null;
    refunded_at: string | null;
    refund_reason: string | null;
}
