// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../index.js";

export interface GetBusinessSubmissionsResponse {
    data: GetBusinessSubmissionsResponse.Data;
}

export namespace GetBusinessSubmissionsResponse {
    export interface Data extends FiveOneEat.CustomerBusinessSubmission {}
}
