// This file was auto-generated by Fern from our API Definition.

export interface CreatePaymentIntentCartResponse {
    status: string;
    client_secret: string;
    payment_intent_id: string;
    subtotal: string;
    tax_amount: string;
    tax_calculation: CreatePaymentIntentCartResponse.TaxCalculation | null;
    shipping_amount: string;
    shipping_method: unknown | null;
    platform_fee: string;
    total_amount: string;
}

export namespace CreatePaymentIntentCartResponse {
    export interface TaxCalculation {
        id: string;
        amount_total: string;
        tax_amount_exclusive: string;
    }
}
