// This file was auto-generated by Fern from our API Definition.

export type GetShippingOptionsCartResponse =
    | {
          options: {
              provider_rate_id: string;
              carrier: string;
              service: string;
              amount: string;
              amount_cents: number;
              currency: string;
              carrier_delivery_days: number | null;
              estimated_delivery_date: string | null;
          }[];
      }
    | {
          options: string[];
      };
