// This file was auto-generated by Fern from our API Definition.

export interface SelectShippingOptionCartResponse {
    shipping_amount: string;
    shipping_amount_cents: number;
    shipping_method: string;
    total_amount: string;
}
