// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         productCategory: "productCategory"
 *     }
 */
export interface DeleteProductCategoriesRequest {
    /** The product category ID */
    productCategory: string;
}
