// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         productCategory: "productCategory"
 *     }
 */
export interface UpdateProductCategoryRequest {
    /** The product category ID */
    productCategory: string;
    name?: string;
    description?: string | null;
    parent_id?: string | null;
    sort_order?: number;
}
