// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         stand: "stand",
 *         variant_id: "variant_id",
 *         quantity: 1
 *     }
 */
export interface CustomerAddStandCartItemRequest {
    /** The stand ID */
    stand: string;
    variant_id: string;
    quantity: number;
}
