// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         menu: "menu",
 *         name: "name"
 *     }
 */
export interface StoreMenuGroupRequest {
    /** The menu ID */
    menu: string;
    name: string;
    description?: string | null;
    sort_order?: number | null;
}
