// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../index.js";

/**
 * @example
 *     {
 *         variant: "variant",
 *         type: "add",
 *         quantity: 1,
 *         reason: "restock"
 *     }
 */
export interface AdjustInventoryRequest {
    /** The variant ID */
    variant: string;
    type: AdjustInventoryRequest.Type;
    quantity: number;
    reason: FiveOneEat.InventoryChangeType;
    notes?: string | null;
}

export namespace AdjustInventoryRequest {
    export const Type = {
        Add: "add",
        Subtract: "subtract",
        Set: "set",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
