// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../../src/api/index";
import { FiveOneEatClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("ModifiersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: { id: "id", name: "name", description: "description", price: 1.1, is_default: true },
        };

        server
            .mockEndpoint()
            .get("/business/items/menuItem/modifiers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.menus.items.modifiers.list({
            menuItem: "menuItem",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/items/menuItem/modifiers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.list({
                menuItem: "menuItem",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/items/menuItem/modifiers")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.list({
                menuItem: "menuItem",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/items/menuItem/modifiers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.list({
                menuItem: "menuItem",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("attach (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1 };
        const rawResponseBody = {
            data: { id: "id", name: "name", description: "description", price: 1.1, is_default: true },
        };

        server
            .mockEndpoint()
            .post("/business/items/menuItem/modifiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.menus.items.modifiers.attach({
            menuItem: "menuItem",
            name: "name",
            price: 1.1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("attach (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/items/menuItem/modifiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.attach({
                menuItem: "menuItem",
                name: "name",
                price: 1.1,
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("attach (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/items/menuItem/modifiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.attach({
                menuItem: "menuItem",
                name: "name",
                price: 1.1,
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("attach (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/items/menuItem/modifiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.attach({
                menuItem: "menuItem",
                name: "name",
                price: 1.1,
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("attach (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", price: 1.1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/items/menuItem/modifiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.attach({
                menuItem: "menuItem",
                name: "name",
                price: 1.1,
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("detach (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Modifier detached successfully." };

        server
            .mockEndpoint()
            .delete("/business/items/menuItem/modifiers/modifier")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.menus.items.modifiers.detach({
            menuItem: "menuItem",
            modifier: "modifier",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("detach (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/items/menuItem/modifiers/modifier")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.detach({
                menuItem: "menuItem",
                modifier: "modifier",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("detach (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/items/menuItem/modifiers/modifier")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.detach({
                menuItem: "menuItem",
                modifier: "modifier",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("detach (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/items/menuItem/modifiers/modifier")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.menus.items.modifiers.detach({
                menuItem: "menuItem",
                modifier: "modifier",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });
});
