// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bulletin: "bulletin",
 *         body: "body"
 *     }
 */
export interface StoreBulletinCommentRequest {
    /** The bulletin ID */
    bulletin: string;
    body: string;
    parent_id?: string | null;
}
