// This file was auto-generated by Fern from our API Definition.

export interface LogoutAllResponse {
    message: LogoutAllResponse.Message;
}

export namespace LogoutAllResponse {
    export const Message = {
        AllTokensRevokedSuccessfully: "All tokens revoked successfully",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
