// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         handle: "katzs-deli"
 *     }
 */
export interface GetBusinessBulletinsRequest {
    /** The business handle */
    handle: string;
    /** Page number for pagination */
    page?: number;
    /** Number of bulletins per page */
    per_page?: number;
}
