// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../../src/api/index";
import { FiveOneEatClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("ConversationsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    business: { id: "id", name: "name", handle: "handle", logo_url: null },
                    last_message: { id: "id", content: "content", created_at: "created_at" },
                    last_message_at: "last_message_at",
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.messaging.conversations.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.list();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("start (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                business: { id: "id", name: "name", handle: "handle", logo_url: "logo_url" },
                last_message: { id: "id", content: "content", created_at: "created_at" },
                last_message_at: "last_message_at",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/messaging/conversations/marios-pizza")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.messaging.conversations.start({
            business: "marios-pizza",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("start (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/messaging/conversations/business")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.start({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("start (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/messaging/conversations/business")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.start({
                business: "business",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                business: { id: "id", name: "name", handle: "handle", logo_url: "logo_url" },
                last_message: { id: "id", content: "content", created_at: "created_at" },
                last_message_at: "last_message_at",
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations/550e8400-e29b-41d4-a716-446655440000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.messaging.conversations.get({
            conversation: "550e8400-e29b-41d4-a716-446655440000",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations/conversation")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.get({
                conversation: "conversation",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/messaging/conversations/conversation")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.get({
                conversation: "conversation",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = 1;

        server
            .mockEndpoint()
            .delete("/customer/messaging/conversations/550e8400-e29b-41d4-a716-446655440000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.messaging.conversations.delete({
            conversation: "550e8400-e29b-41d4-a716-446655440000",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/messaging/conversations/conversation")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.delete({
                conversation: "conversation",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/messaging/conversations/conversation")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.customer.messaging.conversations.delete({
                conversation: "conversation",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });
});
