// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         discount: "discount"
 *     }
 */
export interface GetDiscountsRequest {
    /** The discount ID */
    discount: string;
}
