// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         discount: "discount"
 *     }
 */
export interface UpdateDiscountRequest {
    /** The discount ID */
    discount: string;
    code?: string;
    type?: UpdateDiscountRequest.Type;
    value?: number;
    minimum_purchase?: number | null;
    maximum_discount?: number | null;
    applies_to?: UpdateDiscountRequest.AppliesTo;
    usage_limit?: number | null;
    usage_limit_per_customer?: number | null;
    starts_at?: string | null;
    ends_at?: string | null;
    is_active?: boolean;
    product_ids?: string[] | null;
    category_ids?: string[] | null;
}

export namespace UpdateDiscountRequest {
    export const Type = {
        Percentage: "percentage",
        FixedAmount: "fixed_amount",
        FreeShipping: "free_shipping",
        Bogo: "bogo",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const AppliesTo = {
        All: "all",
        SpecificProducts: "specific_products",
        SpecificCategories: "specific_categories",
    } as const;
    export type AppliesTo = (typeof AppliesTo)[keyof typeof AppliesTo];
}
