// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         photo: "photo"
 *     }
 */
export interface DeleteGalleryRequest {
    /** The photo ID */
    photo: string;
}
