// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         businessList: "businessList"
 *     }
 */
export interface GetListsRequest {
    /** The list uuid */
    businessList: string;
}
