// This file was auto-generated by Fern from our API Definition.

import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CuisinesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/business/cuisines").respondWith().statusCode(200).build();

        const response = await client.business.cuisines.list();
        expect(response).toEqual(undefined);
    });
});
