// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("GalleryClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    url: "url",
                    original_filename: "original_filename",
                    alt_text: "alt_text",
                    sort_order: 1,
                    size: 1,
                    created_at: "created_at",
                },
            ],
        };

        server.mockEndpoint().get("/business/gallery").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.business.gallery.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/business/gallery").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.business.gallery.list();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("reorder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { photos: [{ id: "id", sort_order: 1 }] };
        const rawResponseBody = { message: "Photo order updated successfully." };

        server
            .mockEndpoint()
            .put("/business/gallery/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.gallery.reorder({
            photos: [
                {
                    id: "id",
                    sort_order: 1,
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("reorder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            photos: [
                { id: "id", sort_order: 1 },
                { id: "id", sort_order: 1 },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.reorder({
                photos: [
                    {
                        id: "id",
                        sort_order: 1,
                    },
                    {
                        id: "id",
                        sort_order: 1,
                    },
                ],
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("reorder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            photos: [
                { id: "id", sort_order: 1 },
                { id: "id", sort_order: 1 },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/reorder")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.reorder({
                photos: [
                    {
                        id: "id",
                        sort_order: 1,
                    },
                    {
                        id: "id",
                        sort_order: 1,
                    },
                ],
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                url: "url",
                original_filename: "original_filename",
                alt_text: "alt_text",
                sort_order: 1,
                size: 1,
                created_at: "created_at",
            },
        };

        server
            .mockEndpoint()
            .put("/business/gallery/photo")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.gallery.update({
            photo: "photo",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/photo")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.update({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/photo")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.update({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/photo")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.update({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/business/gallery/photo")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.update({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Photo deleted successfully." };

        server
            .mockEndpoint()
            .delete("/business/gallery/photo")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.gallery.delete({
            photo: "photo",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/gallery/photo")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.delete({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/gallery/photo")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.delete({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/gallery/photo")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.gallery.delete({
                photo: "photo",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });
});
