// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../../src/api/index";
import { FiveOneEatClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("StripeConnectClient", () => {
    test("status (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: 1,
                stripe_account_id: "stripe_account_id",
                charges_enabled: true,
                payouts_enabled: true,
                details_submitted: true,
                is_ready: true,
                is_active: true,
                requirements: [{ key: "value" }],
                capabilities: [{ key: "value" }],
                country: "country",
                default_currency: "default_currency",
                email: "email",
                deauthorized_at: "2024-01-15T09:30:00Z",
                stripe_updated_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            meta: { publishable_key: "publishable_key", onboarding_required: true, requires_action: "requires_action" },
        };

        server
            .mockEndpoint()
            .get("/business/stripe-connect")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.stripeConnect.status();
        expect(response).toEqual(rawResponseBody);
    });

    test("status (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/stripe-connect")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.status();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("status (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/business/stripe-connect")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.status();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("disconnect (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "Stripe account has been disconnected." };

        server
            .mockEndpoint()
            .delete("/business/stripe-connect")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.stripeConnect.disconnect();
        expect(response).toEqual(rawResponseBody);
    });

    test("disconnect (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/stripe-connect")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.disconnect();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("disconnect (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/stripe-connect")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.disconnect();
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("disconnect (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/stripe-connect")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.disconnect();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("createAccountSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { components: [{ enabled: true, features: ["features"] }] };
        const rawResponseBody = { client_secret: "client_secret", expires_at: "expires_at" };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/account-session")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.stripeConnect.createAccountSession({
            components: [
                {
                    enabled: true,
                    features: ["features"],
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAccountSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            components: [
                { enabled: true, features: ["features", "features"] },
                { enabled: true, features: ["features", "features"] },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/account-session")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.createAccountSession({
                components: [
                    {
                        enabled: true,
                        features: ["features", "features"],
                    },
                    {
                        enabled: true,
                        features: ["features", "features"],
                    },
                ],
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("createAccountSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            components: [
                { enabled: true, features: ["features", "features"] },
                { enabled: true, features: ["features", "features"] },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/account-session")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.createAccountSession({
                components: [
                    {
                        enabled: true,
                        features: ["features", "features"],
                    },
                    {
                        enabled: true,
                        features: ["features", "features"],
                    },
                ],
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("refresh (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: 1,
                stripe_account_id: "stripe_account_id",
                charges_enabled: true,
                payouts_enabled: true,
                details_submitted: true,
                is_ready: true,
                is_active: true,
                requirements: [{ key: "value" }],
                capabilities: [{ key: "value" }],
                country: "country",
                default_currency: "default_currency",
                email: "email",
                deauthorized_at: "2024-01-15T09:30:00Z",
                stripe_updated_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            meta: { publishable_key: "publishable_key", onboarding_required: true, requires_action: "requires_action" },
        };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/refresh")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.business.stripeConnect.refresh();
        expect(response).toEqual(rawResponseBody);
    });

    test("refresh (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/refresh")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.refresh();
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("refresh (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/stripe-connect/refresh")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.business.stripeConnect.refresh();
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
