// This file was auto-generated by Fern from our API Definition.

export interface ListCategoriesShopResponse {
    data: ListCategoriesShopResponse.Data.Item[];
}

export namespace ListCategoriesShopResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: string;
            name: string;
            slug: string;
            products_count: string;
        }
    }
}
