// This file was auto-generated by Fern from our API Definition.

export interface ReorderMenuGroupsResponse {
    message: ReorderMenuGroupsResponse.Message;
}

export namespace ReorderMenuGroupsResponse {
    export const Message = {
        GroupsReorderedSuccessfully: "Groups reordered successfully.",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
