// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         business: "business",
 *         bulletin: "bulletin"
 *     }
 */
export interface CreateCommentsRequest {
    business: string;
    bulletin: string;
}
