// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../src/api/index";
import { FiveOneEatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BusinessPushNotificationsClient", () => {
    test("registerBusinessPushToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = {
            id: "id",
            token: "token",
            device_id: "device_id",
            device_name: "device_name",
            platform: "platform",
        };

        server
            .mockEndpoint()
            .post("/business/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessPushNotifications.registerBusinessPushToken({
            token: "token",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("registerBusinessPushToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessPushNotifications.registerBusinessPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("registerBusinessPushToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/business/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessPushNotifications.registerBusinessPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("unregisterBusinessPushToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/business/push-tokens").respondWith().statusCode(200).build();

        const response = await client.businessPushNotifications.unregisterBusinessPushToken({
            token: "token",
        });
        expect(response).toEqual(undefined);
    });

    test("unregisterBusinessPushToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/push-tokens")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessPushNotifications.unregisterBusinessPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("unregisterBusinessPushToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/business/push-tokens")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessPushNotifications.unregisterBusinessPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
