// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../src/api/index";
import { FiveOneEatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BusinessContentClient", () => {
    test("getBusinessMenus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                menus: [
                    {
                        id: "id",
                        name: "name",
                        description: null,
                        groups: [
                            {
                                id: "id",
                                name: "name",
                                description: null,
                                items: [
                                    {
                                        id: "id",
                                        name: "name",
                                        description: null,
                                        price: null,
                                        image: null,
                                        allergens: null,
                                    },
                                ],
                            },
                        ],
                    },
                ],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/menus")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBusinessMenus({
            handle: "katzs-deli",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBusinessMenus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/menus")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessMenus({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getBusinessMenus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/menus")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessMenus({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getBusinessPhotos (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                photos: [{ id: "id", url: "url", alt_text: null }],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/photos")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBusinessPhotos({
            handle: "katzs-deli",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBusinessPhotos (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/photos")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessPhotos({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getBusinessPhotos (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/photos")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessPhotos({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getBusinessBulletins (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                bulletins: [{ id: "id", title: null, content: null, published_at: null }],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/bulletins")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBusinessBulletins({
            handle: "katzs-deli",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBusinessBulletins (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/bulletins")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessBulletins({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getBusinessBulletins (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/bulletins")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessBulletins({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getBulletinComments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                comments: [{ id: "id", body: "body", user: { id: "id", name: "name" }, created_at: null }],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/bulletins/01950e7d-1234-7000-abcd-ef0123456789/comments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBulletinComments({
            handle: "katzs-deli",
            bulletin: "01950e7d-1234-7000-abcd-ef0123456789",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBulletinComments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/bulletins/bulletin/comments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBulletinComments({
                handle: "handle",
                bulletin: "bulletin",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getBulletinComments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/bulletins/bulletin/comments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBulletinComments({
                handle: "handle",
                bulletin: "bulletin",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("getBulletinComments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/bulletins/bulletin/comments")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBulletinComments({
                handle: "handle",
                bulletin: "bulletin",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("createBulletinComment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { body: "body" };
        const rawResponseBody = {
            data: { id: "id", body: "body", user: { id: "id", name: "name" }, created_at: "2024-01-15T09:30:00Z" },
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/katzs-deli/bulletins/01950e7d-1234-7000-abcd-ef0123456789/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.createBulletinComment({
            handle: "katzs-deli",
            bulletin: "01950e7d-1234-7000-abcd-ef0123456789",
            body: "body",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createBulletinComment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { body: "body" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/bulletins/bulletin/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.createBulletinComment({
                handle: "handle",
                bulletin: "bulletin",
                body: "body",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("createBulletinComment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { body: "body" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/bulletins/bulletin/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.createBulletinComment({
                handle: "handle",
                bulletin: "bulletin",
                body: "body",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("createBulletinComment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { body: "body" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/bulletins/bulletin/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.createBulletinComment({
                handle: "handle",
                bulletin: "bulletin",
                body: "body",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getBusinessEvents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                events: [
                    {
                        id: "id",
                        title: "title",
                        description: null,
                        starts_at: "2024-01-15T09:30:00Z",
                        ends_at: "2024-01-15T09:30:00Z",
                        location: null,
                        is_featured: true,
                        ticket_sales_enabled: true,
                        image: null,
                        rsvp_count: 1,
                    },
                ],
                pagination: {
                    current_page: "current_page",
                    per_page: "per_page",
                    total: "total",
                    has_more: "has_more",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBusinessEvents({
            handle: "katzs-deli",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBusinessEvents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/events")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessEvents({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("getBusinessEvents (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/events")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessEvents({
                handle: "handle",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("getBusinessEvent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                title: "title",
                description: "description",
                starts_at: "starts_at",
                ends_at: "ends_at",
                location: "location",
                is_featured: true,
                ticket_sales_enabled: true,
                image: "image",
                rsvp_count: 1,
                user_rsvp_status: "user_rsvp_status",
                user_has_tickets: true,
                ticket_price_from: "ticket_price_from",
                ticket_types: [
                    {
                        id: "id",
                        name: "name",
                        description: null,
                        price: "price",
                        remaining_quantity: null,
                        is_available_for_sale: true,
                        sales_start_at: null,
                        sales_end_at: null,
                    },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/customer/businesses/katzs-deli/events/event")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.getBusinessEvent({
            handle: "katzs-deli",
            event: "event",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBusinessEvent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/events/event")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.getBusinessEvent({
                handle: "handle",
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("storeEventRsvp (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { status: "attending" };
        const rawResponseBody = {
            data: {
                id: "id",
                status: "status",
                notes: "notes",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/customer/businesses/katzs-deli/events/01950e7d-1234-7000-abcd-ef0123456789/rsvp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.storeEventRsvp({
            handle: "katzs-deli",
            event: "01950e7d-1234-7000-abcd-ef0123456789",
            status: "attending",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("storeEventRsvp (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { status: "attending" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/events/event/rsvp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.storeEventRsvp({
                handle: "handle",
                event: "event",
                status: "attending",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("storeEventRsvp (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { status: "attending" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/events/event/rsvp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.storeEventRsvp({
                handle: "handle",
                event: "event",
                status: "attending",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });

    test("storeEventRsvp (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { status: "attending" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/businesses/handle/events/event/rsvp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.storeEventRsvp({
                handle: "handle",
                event: "event",
                status: "attending",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("destroyEventRsvp (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = 1;

        server
            .mockEndpoint()
            .delete("/customer/businesses/katzs-deli/events/01950e7d-1234-7000-abcd-ef0123456789/rsvp")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.businessContent.destroyEventRsvp({
            handle: "katzs-deli",
            event: "01950e7d-1234-7000-abcd-ef0123456789",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("destroyEventRsvp (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/businesses/handle/events/event/rsvp")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.destroyEventRsvp({
                handle: "handle",
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("destroyEventRsvp (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/businesses/handle/events/event/rsvp")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.businessContent.destroyEventRsvp({
                handle: "handle",
                event: "event",
            });
        }).rejects.toThrow(FiveOneEat.NotFoundError);
    });
});
