// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../src/api/index";
import { FiveOneEatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GetPickupTimeslotsClient", () => {
    test("businesses.getPickupTimeslots (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { date: "date", timeslots: [{ key: "value" }] };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/pickup-timeslots")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.getPickupTimeslots.businessesGetPickupTimeslots({
            handle: "handle",
            date: "2023-01-15",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("businesses.getPickupTimeslots (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/pickup-timeslots")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.getPickupTimeslots.businessesGetPickupTimeslots({
                handle: "handle",
                date: "2023-01-15",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("businesses.getPickupTimeslots (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/customer/businesses/handle/pickup-timeslots")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.getPickupTimeslots.businessesGetPickupTimeslots({
                handle: "handle",
                date: "2023-01-15",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
