// This file was auto-generated by Fern from our API Definition.

import * as FiveOneEat from "../../src/api/index";
import { FiveOneEatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PushNotificationsClient", () => {
    test("registerPushToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = {
            id: "id",
            token: "token",
            device_id: "device_id",
            device_name: "device_name",
            platform: "platform",
        };

        server
            .mockEndpoint()
            .post("/customer/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pushNotifications.registerPushToken({
            token: "token",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("registerPushToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pushNotifications.registerPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("registerPushToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/customer/push-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pushNotifications.registerPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });

    test("unregisterPushToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/customer/push-tokens").respondWith().statusCode(200).build();

        const response = await client.pushNotifications.unregisterPushToken({
            token: "token",
        });
        expect(response).toEqual(undefined);
    });

    test("unregisterPushToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/push-tokens")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pushNotifications.unregisterPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnauthorizedError);
    });

    test("unregisterPushToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FiveOneEatClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/customer/push-tokens")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pushNotifications.unregisterPushToken({
                token: "token",
            });
        }).rejects.toThrow(FiveOneEat.UnprocessableEntityError);
    });
});
