// This file was auto-generated by Fern from our API Definition.

import { BusinessClient } from "./api/resources/business/client/Client.js";
import { CustomerClient } from "./api/resources/customer/client/Client.js";
import { CustomerStandsClient } from "./api/resources/customerStands/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace FiveOneEatClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FiveOneEatClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FiveOneEatClient.Options>;
    protected _customer: CustomerClient | undefined;
    protected _customerStands: CustomerStandsClient | undefined;
    protected _business: BusinessClient | undefined;

    constructor(options: FiveOneEatClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get customer(): CustomerClient {
        return (this._customer ??= new CustomerClient(this._options));
    }

    public get customerStands(): CustomerStandsClient {
        return (this._customerStands ??= new CustomerStandsClient(this._options));
    }

    public get business(): BusinessClient {
        return (this._business ??= new BusinessClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
