// This file was auto-generated by Fern from our API Definition.

import type * as FiveOneEat from "../../../../../index.js";

export type ClaimViaTokenClaimsResponse =
    | {
          data: FiveOneEat.ClaimableBusiness;
      }
    | string;
