// This file was auto-generated by Fern from our API Definition.

export interface DeleteTemporaryLocationsResponse {
    message: DeleteTemporaryLocationsResponse.Message;
}

export namespace DeleteTemporaryLocationsResponse {
    export const Message = {
        TemporaryLocationDeletedSuccessfully: "Temporary location deleted successfully.",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
