// This file was auto-generated by Fern from our API Definition.

export interface DeleteImagesResponse {
    message: DeleteImagesResponse.Message;
}

export namespace DeleteImagesResponse {
    export const Message = {
        ImageDeletedSuccessfully: "Image deleted successfully.",
    } as const;
    export type Message = (typeof Message)[keyof typeof Message];
}
